EXTENSION = pg_z
DATA = pg_z--1.0.sql
MODULE_big = pg_z

BUILD_DIR = tmp
SRC_MODULES = pg_z mem_manager
ALGO_MODULES = brotli gzip lz4 snappy zstd

REGRESS = core db_params


ifeq ($(filter $(BUILD_DIR),$(notdir $(CURDIR))),)
-include Makefile.port

all:
	$(MAKE) -C $(BUILD_DIR) -f ../Makefile VPATH=..
	@$(MAKE) -f Makefile assemble-sql

debug:
	$(MAKE) -C $(BUILD_DIR) -f ../Makefile VPATH=.. DEBUG_BUILD=1
	@$(MAKE) -f Makefile assemble-sql

assemble-sql:
	@if [ "$(CONFIGURE_RUN)" = "yes" ]; then \
		ACTIVE_ALGOS="$(patsubst -DUSE_%,%,$(COMPRESSION_CFLAGS))"; \
		echo "-- Autogenerated by Makefile, do not edit" > $(DATA); \
		echo '\\echo Use "CREATE EXTENSION pg_z" to load this file. \\quit' >> $(DATA); \
		cat sql/add_core.sql >> $(DATA); \
		for algo in $$ACTIVE_ALGOS; do \
			if [ -f "sql/add_$$algo.sql" ]; then \
				echo "" >> $(DATA); \
				echo "-- =========================================" >> $(DATA); \
				echo "-- $$algo Functions" >> $(DATA); \
				echo "-- =========================================" >> $(DATA); \
				cat "sql/add_$$algo.sql" >> $(DATA); \
			fi; \
		done; \
	fi

install:
	@$(MAKE) -f Makefile assemble-sql
	$(MAKE) -C $(BUILD_DIR) -f ../Makefile VPATH=.. install

installcheck:
	$(MAKE) -C $(BUILD_DIR) -f ../Makefile VPATH=.. installcheck

clean: clean-artifacts
	$(MAKE) -C $(BUILD_DIR) -f ../Makefile VPATH=.. clean

clean-artifacts:
	rm -f $(DATA) $(BUILD_DIR)/*.o $(BUILD_DIR)/*.bc $(BUILD_DIR)/*.so

else
OBJS = $(addsuffix .o, $(SRC_MODULES))

-include ../Makefile.port

# Enforce that configure must be run beforehand
ifndef CONFIGURE_RUN
$(error Please run ./configure before running make)
endif

ACTIVE_ALGOS = $(patsubst -DUSE_%,%,$(COMPRESSION_CFLAGS))
OBJS    += $(addsuffix .o, $(ACTIVE_ALGOS))
REGRESS += $(ACTIVE_ALGOS)
#REGRESS += $(foreach m,$(ACTIVE_ALGOS),$(m)_compress $(m)_decompress)

$(info OBJS is $(OBJS))
$(info REGRESS is $(REGRESS))

ifdef DEBUG_BUILD
	PG_CFLAGS += -g3 -O0
	STRIP_CMD = :
else
	# O3 - maximum optimization
	# march=native - to use hardware acceleration where possible
	# For example, Snappy uses HW-accelerated CRC32C
	#
	# lto - Link-Time Optimization
	PG_CFLAGS += -march=native -flto
	SHLIB_LINK += -flto
	STRIP_CMD = strip --strip-unneeded $(shlib)
endif

PG_CFLAGS += $(COMPRESSION_CFLAGS)

PG_LDFLAGS += -L/usr/lib/x86_64-linux-gnu
SHLIB_LINK += -Wl,-Bstatic  -Wl,--start-group $(STATIC_LIBS) -Wl,--end-group \
			  -Wl,-Bdynamic $(DYNAMIC_LIBS)

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)


# Strip debug info during "make" or "make debug" only.
# "make install" just copies what was produced
ifneq ($(filter install,$(MAKECMDGOALS)),install)
all: $(shlib)
	@$(STRIP_CMD)
endif

endif
